#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_version 2.0
#db_capb backup

PREVSTATE=1
STATE=1
while [ "$STATE" != "0" ]; do

	case "$STATE" in
		1) # install now or later?
			db_input high openra-data/install || true
			NEXTSTATE=2
			PREVSTATE=0
			;;
		2) # select cdrom path
			db_get openra-data/install
			if [ "$RET" = "false" ]; then
				exit 0
			fi
			db_input high openra-data/cdrom || true
			NEXTSTATE=0
			PREVSTATE=1
			;;
	esac

	# debconf is GO!
	if db_go; then
		STATE=$NEXTSTATE
	else
		STATE=$PREVSTATE
	fi

done
